import 'bootstrap/dist/css/bootstrap.min.css';
import type { Metadata } from 'next';
import './globals.css';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import { Toaster } from 'react-hot-toast';
import { StoreProvider } from '@/lib/redux/provider';
import { FullPageLoading } from '@/components';
import { PageSwitchComponent } from '@/components/page-switch-component';

export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
  title: 'Bespoke Cashmeres',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <Toaster position="top-right" />
          <StoreProvider>
            <FullPageLoading />
            <PageSwitchComponent />
            {children}
          </StoreProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
