export * from './category.d';
export * from './hero.d';
export * from './marquee.d';
export * from './menu.d';
export * from './offgift.d';
export * from './accessories.d';
export * from './favourite.d';
export * from './stories.d';
export * from './instagram.d';
